### ISSUE TITLE
URL update not works

### ISSUE THREAD

**Issue by doiftrue** [maciejbis/Permalink-Manager#6]
![image](https://user-images.githubusercontent.com/15121552/197798351-22d7c5e6-a391-411f-a6e3-7b19f0ef737f.png)

Truing to change this but nothing works.

I investigate the problem and found that another plugin switches blogs and after this operation the `global $permalink_manager_uris` becomes `false` but not `array`. So we need to add default values for switching here:

![image](https://user-images.githubusercontent.com/15121552/197798102-acc39770-cd32-44ec-baea-2ec6448722f3.png)

As it's done here:

![image](https://user-images.githubusercontent.com/15121552/197957840-a7e54b05-2016-45e9-b3d1-fb4147daac5c.png)

- This bug occurs only if `permalink-manager-uris` option is not set and `switch_blog` action was triggered.

**Comment by maciejbis** [comment]
Hi @doiftrue,

As suggested, I implemented this change in 2.3.1 version:
https://github.com/maciejbis/Permalink-Manager/blob/master/includes/core/permalink-manager-helper-functions.php#L917
