### ISSUE TITLE
Trying to access array offset on null in permalink-manager-language-plugins.php:430

### ISSUE THREAD

**Issue by eartahhj** [maciejbis/Permalink-Manager#8]
Using Permalink Manager Lite with WPML, not sure why this happens but the fix is recommended anyway, because checking the array with !empty or with null coalescing would be better anyway.
```
<b>Warning</b>:  Trying to access array offset on null in <b>/var/www/.../plugins/permalink-manager/includes/integrations/permalink-manager-language-plugins.php</b> on line <b>430</b><br />
```

I would recommend this solution:
Current:
`} elseif ( $translate_press_settings['url-slugs'] ) {`
New:
`} elseif ( !empty($translate_press_settings['url-slugs']) ) {`
Alternative:
`} elseif ( $translate_press_settings['url-slugs'] ?? null ) {`

**Comment by eartahhj** [comment]
Opened PR https://github.com/maciejbis/Permalink-Manager/pull/9

**Comment by maciejbis** [comment]
Thank you, this bug will be addressed in the next plugin's release.
